### PR TITLE
Implement Bulk Upload API Support and make typecast work with batch requests

### PR DESCRIPTION
**Pull request by jws325**
This is an implementation of https://github.com/gtalarico/airtable-python-wrapper/issues/35

1. insert, update, and delete can now do up to 10 rows in a single request
2. added batch_update
3. batch_insert, batch_update, and batch_delete make one request per 10 records
4. batch methods now support typecast

### CODE REVIEW

**Comment by gtalarico** [comment]
Why is diff not showing correctly...? 🤔 
Looks like 100% of the file is changed

**Comment by jws325** [comment]
I wrote this with Pycharm on Windows.
Maybe it changed the line endings from Unix to Windows style?

**Comment by gtalarico** [comment]
Sorry but hard to merge this without a diff.
I merge a bunch of dangling PRs we will need to fix this before merging.

I am suprised Pycharm didn't respect `.editorconfg` settings which defines line ending type?
https://github.com/gtalarico/airtable-python-wrapper/blob/master/.editorconfig#L8

Maybe this 👇 
https://stackoverflow.com/questions/41518677/how-to-apply-editorconfig-to-existing-project-in-intellige

**Comment by alonshavit** [comment]
Any plans to merge this soon?

**Comment by gtalarico** [comment]
I think batch api has been added in some form.
sorry we weren't able to use this, but thank you for your contribution.

**Pull request closed without merging**
