### PR TITLE
add batch update method

### PR DESCRIPTION
**Pull request by thomasopsomer**

### CODE REVIEW

**Comment by thomasopsomer** [comment]
Sorry it wasn't intended :)

**Comment by KshitizGIT** [comment]
Why has not this been merged ?

**Comment by thomasopsomer** [comment]
It was just a test on my side... there is something wrong, git thinks I modified the whole file (I guess some end of line weird stuff). I'll post another cleaner PR @KshitizGIT :)

**Comment by gtalarico** [comment]
> Why has not this been merged ?

@KshitizGIT PR changes line ending character in entire file.
Can't be merged as is

**Pull request closed without merging**
